<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="PRG_1_PlcTask" Id="{9c76104d-f8df-400f-b9a4-81d3480ca015}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_1_PlcTask
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_2_PMPS_PRE();

PRG_IM1K1_PPM();
PRG_IM2K1_PPM();
PRG_ST1K1_ZOS();
PRG_IM1K2_PPM();
PRG_IM2K2_PPM();
PRG_IM3K2_PPM();
PRG_IM4K2_PPM();
PRG_TM1K2_ATM();
PRG_IM5K2_PPM();


PRG_3_PMPS_POST();
PRG_4_LOG();]]></ST>
    </Implementation>
    <LineIds Name="PRG_1_PlcTask">
      <LineId Id="3" Count="5" />
      <LineId Id="20" Count="2" />
      <LineId Id="9" Count="0" />
      <LineId Id="23" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>