<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PRG_4_LOG" Id="{1b7dc8ee-ec86-4b1d-931e-b63fb540975f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_4_LOG
VAR
    fbLogHandler: FB_LogHandler;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbLogHandler();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>